version: '3'
services:
  php:
    build: php
    expose:
      - '9000'
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/symfony:cached
      - ./logs:/var/log
  nginx:
    build: nginx
    ports:
      - 80:80
    depends_on:
      - php
      - db
    volumes:
      - ./:/var/www/html/symfony:cached
      - ./logs/nginx/:/var/log/nginx
  db:
    image: postgres
    environment:
      DATABASE_URL: "pgsql://postgres:password@db:5432/astrolab"
    ports:
      - "54320:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data