version: '3'
services:
  php:
    build: php
    expose:
      - '9000'
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/symfony:cached
      - ./logs:/var/log
  nginx:
    build: nginx
    ports:
      - 80:80
    depends_on:
      - php
      - db
    volumes:
      - ./:/var/www/html/symfony:cached
      - ./logs/nginx/:/var/log/nginx
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_HOST=astro-lab_db_1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=astrolab
    volumes:
      - ./postgres-data:/var/lib/postgresql/data